language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - mysql

before_script:
  - composer install

script:
  - vendor/bin/phpcs --standard=PSR2 src/ test/
  - mkdir -p build/logs
  - mysql -e 'create database mysql_test;'
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v